---
- hosts: brokers
  vars:
    sudouser: "{{ ansible_env['SUDO_USER'] }}"
  become: true

  tasks:
  - name: Stop Kafka
    systemd:
      name: kafka
      state: stopped
      enabled: true

  - name: Stop zookeeper
    systemd:
      name: zookeeper
      state: stopped
      enabled: true


